### PR TITLE
Fixed #61: Remove caching form sitemap headers

### LINKED ISSUE #61: Stop adding Cache Control of 1 year for the Sitemap pages
Currently a Cache-Control header of `Cache-Control: max-age=31536000` is being added to the `xml` and `xsl` files by Rankmath, which basically tell the browser/CDN to cache the sitemaps, which is a really bad approach as sitemaps should never be cached as it contains always changing dynamic content.

If you want to keep it, don't set it by default instead give an option to the user asking if they want to add cache control to the sitemaps or not. Moreover adding this cache-control via PHP prevents users to overwrite it via server rule like `nginx.conf` as Nginx will add the header first and then PHP will overwrite it.

The cache-control is being added from `/seo-by-rank-math/includes/modules/sitemap/abstract-xml.php` line no `48` from this function:

```php
protected function send_headers( $headers = [] ) {
  $expires  = gmdate( 'D, d M Y H:i:s', ( time() + YEAR_IN_SECONDS ) );
  $defaults = [
    'X-Robots-Tag'  => 'noindex',
    'Content-Type'  => 'text/xml; charset=' . $this->get_output_charset(),
    'Pragma'        => 'public',
    'Cache-Control' => 'maxage=' . YEAR_IN_SECONDS, // <-- THIS LINE
    'Expires'       => $expires . ' GMT',
    'Etag'          => md5( $expires . $this->type ),
  ];

  $headers = wp_parse_args( $headers, $defaults );

  header( $this->get_protocol() . ' 200 OK', true, 200 );

  foreach ( $headers as $header => $value ) {
    header( $header . ': ' . $value );
  }
}
```

Please stop adding cache-control by default. The plugin should never add the cache-control and if any user needs they can add the respective htaccess or nginx rules for that in the server.

### PR DESCRIPTION
**Pull request by marcwiest**
Closes/Fixes #61

### CODE REVIEW

**Comment by isaumya** [comment]
Hey guys any update on this PR? This really needs to be fixed asap.

**Comment by balazsmts** [comment]
Hi @isaumya 
This issue will be fixed in the next update for Rank Math. Until then, you can just fix it in your own copy by applying the same changes as in this PR.
Hope that helps.

**Comment by isaumya** [comment]
Hi @balazsmts,
That's exactly what I wanted to hear as I've already made the manual changes inside the code even before the PR was pushed. So, if the fix is not added in the upcoming release I have to do it all over again for all of our client sites. :)
Thanks. :)

**Comment by isaumya** [comment]
Hey @balazsmts & @marcwiest,
I have been doing some thorough testing and found that when `cache-control` is removed from the PHP, no matter how hard we try to add a `cache-control` header using nginx or whatever it doesn't work as the `sitemap_index.xml` file doesn't actually exists physically and instead generated by PHP.

So, I think instead of simply removing the `cache-control` header we should add 

```
'Cache-Control' => 'no-cache, no-store, must-revalidate, max-age=0'
```

Same thing for `robots.txt. As when that file is also getting generated dynamically via PHP using [robots_txt filter](https://developer.wordpress.org/reference/hooks/robots_txt/) there is no `cache-control` header and adding a cache-control at the server rules doesn't help as to server the file doesn't exist and it is processed via PHP.

**Pull request closed without merging**
